version: '3.9'

services:
  patient-service-database:
    image: mysql:latest
    container_name: patient-service-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: patientdb
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
      interval: 5s
      retries: 10
    networks:
      - patient-network
  auth-service-database:
    image: mysql:latest
    container_name: auth-service-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: authdb
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
      interval: 5s
      retries: 10
    networks:
      - patient-network

  auth-service:
    build: ./auth-service
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://auth-service-database:3306/authdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      JWT_SECRET: IxQm+Ew8bxKzs9TXn8U/sILSfJrUBrngc0E0qXyL8yK8K/2IRK3xrdfV3VlpWg74ymoH5Rovfi5WilAgY/hYvw==

    depends_on:
      auth-service-database:
          condition: service_healthy
    ports:
      - "4005:4005"
    networks:
      patient-network:

  patient-service:
    build: ./patient-service
    container_name: patient-service
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://patient-service-database:3306/patientdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    ports:
      - "5005:5005"
    depends_on:
      patient-service-database:
        condition: service_healthy
    networks:
      - patient-network

  billing-service:
    build: ./billing-service
    container_name: billing-service
    restart: always
    environment:
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001
    ports:
      - "4001:4001"   # REST endpoint (if any)
      - "9001:9001"   # gRPC endpoint
    networks:
      - patient-network

  analytics-service:
    build: ./analytics-service
    container_name: analytics-service
    restart: always
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006"
    ports:
      - "4002:4002"
      - "5006:5006"
    depends_on:
      - kafka
    networks:
      - patient-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: always
    environment:
      AUTH_SERVICE_URL: http://auth-service:4005
    ports:
      - "4004:4004"
    networks:
      - patient-network
    depends_on:
      - patient-service


  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:9094,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - patient-network


networks:
  patient-network:
    driver: bridge